// autocert-providers-gen keeps provider types, schemas, and documentation in sync.
package main

import (
	"bytes"
	"encoding/json/v2"
	"flag"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/yusing/godoxy/internal/autocert"
	"github.com/yusing/godoxy/internal/dnsproviders"
)

const typePath = "webui/src/types/godoxy/config/autocert-providers.ts"
const startMarker = "[autocert-providers-start]: #"
const endMarker = "[autocert-providers-end]: #"

var docPaths = []string{
	"internal/autocert/README.md",
	"internal/dnsproviders/README.md",
	"webui/wiki/content/docs/impl/internal-autocert.mdx",
	"webui/wiki/content/docs/impl/internal-dnsproviders.mdx",
	"webui/wiki/content/docs/godoxy/getting-started/DNS-01-Providers.mdx",
}

func providerNames() []string {
	dnsproviders.InitProviders()
	names := slices.Collect(maps.Keys(autocert.Providers))
	names = slices.DeleteFunc(names, func(name string) bool {
		return name == autocert.ProviderPseudo || name == autocert.ProviderCustom
	})
	names = append(names, autocert.ProviderCustom)
	slices.Sort(names)
	return names
}

func renderType(names []string) []byte {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by shadowtree gen-autocert-providers. Do not edit.")
	fmt.Fprintln(&b, "export type AutocertProvider =")
	for _, name := range names {
		fmt.Fprintf(&b, "  | '%s'\n", name)
	}
	return []byte(b.String())
}

func renderTable(names []string) string {
	var b strings.Builder
	fmt.Fprintln(&b, startMarker)
	fmt.Fprintln(&b, "\nGenerated from the bundled provider registry with `shadowtree gen-autocert-providers`.")
	fmt.Fprintln(&b, "\n| Provider ID | Configuration reference |\n| --- | --- |")
	for _, name := range names {
		ref := fmt.Sprintf("[lego %s](https://go-acme.github.io/lego/dns/%s/)", name, name)
		switch name {
		case autocert.ProviderLocal:
			ref = "Existing certificate files (`cert_path` and `key_path`); no ACME"
		case autocert.ProviderCustom:
			ref = "Custom ACME CA (`ca_dir_url`)"
		case "rfc2136":
			ref = "Alias for `dnsupdate`"
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", name, ref)
	}
	fmt.Fprintln(&b, "\n`pseudo` is internal and is not offered in the picker. Only the bundled DNS providers above are supported; lego's full catalogue includes providers that GoDoxy does not bundle.")
	fmt.Fprintln(&b, "\n"+endMarker)
	return b.String()
}

func replaceTable(current []byte, table string) ([]byte, error) {
	s := string(current)
	start := strings.Index(s, startMarker)
	end := strings.Index(s, endMarker)
	if start < 0 || end < start || strings.Count(s, startMarker) != 1 || strings.Count(s, endMarker) != 1 {
		return nil, fmt.Errorf("expected one ordered provider table marker pair")
	}
	end += len(endMarker)
	return []byte(s[:start] + strings.TrimSuffix(table, "\n") + s[end:]), nil
}

func updateFile(root, path string, want []byte, check bool) error {
	fullPath := filepath.Join(root, path)
	if check {
		current, err := os.ReadFile(fullPath)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		if !bytes.Equal(current, want) {
			return fmt.Errorf("%s is stale; run shadowtree gen-autocert-providers", path)
		}
		return nil
	}
	return os.WriteFile(fullPath, want, 0644)
}

type schema struct {
	Ref         string            `json:"$ref"`
	Const       string            `json:"const"`
	Enum        []string          `json:"enum"`
	AnyOf       []schema          `json:"anyOf"`
	Properties  map[string]schema `json:"properties"`
	Definitions map[string]schema `json:"definitions"`
}

func schemaProviders(s schema, defs map[string]schema) ([]string, error) {
	if s.Ref != "" {
		name, ok := strings.CutPrefix(s.Ref, "#/definitions/")
		def, found := defs[name]
		if !ok || !found {
			return nil, fmt.Errorf("unknown schema reference %q", s.Ref)
		}
		return schemaProviders(def, defs)
	}
	if len(s.AnyOf) > 0 {
		var names []string
		for _, branch := range s.AnyOf {
			values, err := schemaProviders(branch, defs)
			if err != nil {
				return nil, err
			}
			names = append(names, values...)
		}
		return names, nil
	}
	if provider, ok := s.Properties["provider"]; ok {
		return schemaProviders(provider, defs)
	}
	if s.Const != "" {
		return []string{s.Const}, nil
	}
	if len(s.Enum) > 0 {
		return s.Enum, nil
	}
	return nil, fmt.Errorf("provider must have a finite const or enum, not an unrestricted string")
}

func checkSchemas(root string, want []string) error {
	for _, file := range []string{"autocert.schema.json", "config.schema.json"} {
		path := "webui/src/types/godoxy/" + file
		data, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		var doc schema
		if err := json.Unmarshal(data, &doc); err != nil {
			return fmt.Errorf("decode %s: %w", path, err)
		}
		types := []string{"AutocertConfigWithoutExtra"}
		if strings.HasPrefix(file, "config.") {
			types = []string{"AutocertConfig", "AutocertExtra"}
		}
		for _, name := range types {
			got, err := schemaProviders(doc.Definitions[name], doc.Definitions)
			slices.Sort(got)
			got = slices.Compact(got)
			if err != nil || !slices.Equal(got, want) {
				return fmt.Errorf("%s %s provider schema is stale (%v); run shadowtree gen-autocert-providers", path, name, err)
			}
		}
	}
	return nil
}

func generate(root string, check bool) error {
	names := providerNames()
	if err := updateFile(root, typePath, renderType(names), check); err != nil {
		return err
	}
	for _, path := range docPaths {
		current, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		want, err := replaceTable(current, renderTable(names))
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		if err := updateFile(root, path, want, check); err != nil {
			return err
		}
	}
	if check {
		return checkSchemas(root, names)
	}
	return nil
}

func main() {
	check := flag.Bool("check", false, "fail if provider types, schemas, or documentation have drifted")
	root := flag.String("root", ".", "repository root")
	flag.Parse()
	if err := generate(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
