// Code generated by gen.py; DO NOT EDIT.

package autocert

func init() {
	registerPlaceholderProviders(
		"local",
		"pseudo",
		"acmedns",
		"azuredns",
		"cloudflare",
		"cloudns",
		"clouddns",
		"digitalocean",
		"duckdns",
		"edgedns",
		"gcloud",
		"godaddy",
		"googledomains",
		"hetzner",
		"hostinger",
		"httpreq",
		"ionos",
		"inwx",
		"linode",
		"namecheap",
		"netcup",
		"netlify",
		"oraclecloud",
		"ovh",
		"porkbun",
		"rfc2136",
		"scaleway",
		"spaceship",
		"vercel",
		"vultr",
		"timewebcloud",
	)
}
