package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	godoxy "github.com/yusing/godoxy/internal/env"
)

func TestRenderIndependentOfEnvironment(t *testing.T) {
	example, wiki := render()
	for _, d := range godoxy.Definitions() {
		for _, prefix := range []string{"GODOXY_", "GOPROXY_", ""} {
			t.Setenv(prefix+d.Name, "render-must-not-read-this-value")
		}
	}
	nextExample, nextWiki := render()
	if !bytes.Equal(example, nextExample) || !bytes.Equal(wiki, nextWiki) {
		t.Fatal("generated documentation changed with process environment")
	}
}

func TestRenderRegistryDefaultsAndDeploymentExamples(t *testing.T) {
	example, wiki := render()
	for _, line := range strings.Split(string(example), "\n") {
		if line != "" && !strings.HasPrefix(line, "#") {
			if _, _, ok := strings.Cut(line, "="); !ok {
				t.Errorf("uncommented line is not an environment assignment: %q", line)
			}
		}
	}
	for _, d := range godoxy.Definitions() {
		name := "GODOXY_" + d.Name
		if d.Compose {
			name = d.Name
		}
		value := d.Default
		if d.Example != "" {
			value = d.Example
		}
		prefix := "# "
		if d.Required {
			prefix = ""
		}
		line := fmt.Sprintf("%s%s=%s\n", prefix, name, value)
		if !bytes.Contains(example, []byte("\n"+line)) {
			t.Errorf("example missing registry assignment for %s", name)
		}
		def := "`" + d.Default + "`"
		if d.Default == "" {
			def = "empty"
		}
		row := fmt.Sprintf("| `%s` | %s | %s | %s |\n", name, d.Type, def, d.Description)
		if !bytes.Contains(wiki, []byte(row)) {
			t.Errorf("wiki missing registry default row for %s", name)
		}
	}
	for _, note := range []string{"Go test executables", "explicit false", "TRACE", "effective `DEBUG`", "test-derived debug", "Empty values fall through"} {
		if !bytes.Contains(wiki, []byte(note)) {
			t.Errorf("wiki missing dynamic default explanation: %s", note)
		}
	}
	if !bytes.Contains(example, []byte("\nGODOXY_DOCKER_HOST=tcp://${LISTEN_ADDR}\n")) ||
		!bytes.Contains(wiki, []byte("`unix:///var/run/docker.sock`")) {
		t.Fatal("deployment Docker endpoint must differ from the documented built-in default")
	}
}

func TestGenerateWritesDeterministicallyAndChecksDrift(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Dir(filepath.Join(root, wikiPath)), 0755); err != nil {
		t.Fatal(err)
	}
	example, wiki := render()
	want := map[string][]byte{".env.example": example, wikiPath: wiki}
	if err := generate(root, true); err == nil || !strings.Contains(err.Error(), ".env.example") {
		t.Fatal("check must report missing example")
	}
	if _, err := os.Stat(filepath.Join(root, ".env.example")); !os.IsNotExist(err) {
		t.Fatal("check must not create missing files")
	}
	for range 2 {
		if err := generate(root, false); err != nil {
			t.Fatal(err)
		}
		for path, data := range want {
			current, err := os.ReadFile(filepath.Join(root, path))
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(current, data) {
				t.Errorf("generated bytes differ for %s", path)
			}
		}
		if err := generate(root, true); err != nil {
			t.Fatal(err)
		}
	}
	for _, path := range []string{".env.example", wikiPath} {
		t.Run(path, func(t *testing.T) {
			fullPath := filepath.Join(root, path)
			stale := []byte("stale documentation\n")
			if err := os.WriteFile(fullPath, stale, 0644); err != nil {
				t.Fatal(err)
			}
			if err := generate(root, true); err == nil || !strings.Contains(err.Error(), path) {
				t.Fatal("check must identify the stale file")
			}
			current, err := os.ReadFile(fullPath)
			if err != nil || !bytes.Equal(current, stale) {
				t.Fatal("check modified a stale file")
			}
			if err := generate(root, false); err != nil {
				t.Fatal(err)
			}
			if err := os.Remove(fullPath); err != nil {
				t.Fatal(err)
			}
			if err := generate(root, true); err == nil || !strings.Contains(err.Error(), path) {
				t.Fatal("check must identify the missing file")
			}
			if _, err := os.Stat(fullPath); !os.IsNotExist(err) {
				t.Fatal("check recreated a missing file")
			}
			if err := generate(root, false); err != nil {
				t.Fatal(err)
			}
		})
	}
}
