package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

const (
	cfIPv4CIDRsEndpoint = "https://www.cloudflare.com/ips-v4"
	cfIPv6CIDRsEndpoint = "https://www.cloudflare.com/ips-v6"
	defaultOutPath      = "internal/net/gphttp/middleware/cloudflare_real_ip_seed_gen.go"
	requestTimeout      = 10 * time.Second
)

func main() {
	outPath := defaultOutPath
	if len(os.Args) > 1 {
		for i := 1; i < len(os.Args); i++ {
			switch os.Args[i] {
			case "-out":
				if i+1 >= len(os.Args) {
					fatalf("missing value for -out")
				}
				i++
				outPath = os.Args[i]
			default:
				fatalf("unknown argument %q", os.Args[i])
			}
		}
	}

	cidrs, err := fetchCloudflareCIDRs()
	if err != nil {
		fatalf("fetch Cloudflare CIDRs: %v", err)
	}

	source, err := renderGeneratedSource(cidrs)
	if err != nil {
		fatalf("render generated source: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if current, err := os.ReadFile(outPath); err == nil && bytes.Equal(current, source) {
		return
	}
	if err := os.WriteFile(outPath, source, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func fetchCloudflareCIDRs() ([]byte, error) {
	var all bytes.Buffer
	for _, endpoint := range []string{cfIPv4CIDRsEndpoint, cfIPv6CIDRsEndpoint} {
		body, err := fetchEndpoint(endpoint)
		if err != nil {
			return nil, err
		}
		all.Write(body)
		if all.Len() > 0 && all.Bytes()[all.Len()-1] != '\n' {
			all.WriteByte('\n')
		}
	}
	return all.Bytes(), nil
}

func fetchEndpoint(endpoint string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, err
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s returned HTTP %d", endpoint, resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return body, nil
}

func renderGeneratedSource(cidrs []byte) ([]byte, error) {
	raw := fmt.Sprintf(`// Code generated by cmd/cloudflare-cidrs-gen. DO NOT EDIT.

package middleware

func init() {
	generatedCloudflareCIDRsRaw = []byte(%s)
}
`, strconv.Quote(string(cidrs)))
	return format.Source([]byte(raw))
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
